/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adam.convertcurrency;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Bodie
 */
public class AUDinfo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form AUDinfo
     */
    static String aud5c = "AUD5c";
    static String aud10c = "AUD10c";
    static String aud20c = "AUD20c";
    static String aud50c = "AUD50c";
    static String aud1 = "AUD$1";
    static String aud2 = "AUD$2";
    static String aud5 = "AUD$5";
    static String aud10 = "AUD$10";
    static String aud20 = "AUD$20";
    static String aud50 = "AUD$50";
    static String aud100 = "AUD$100";
    private static Component JFrame;
    
    public AUDinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audButtonGroup = new javax.swing.ButtonGroup();
        audInfoTab = new javax.swing.JTabbedPane();
        infoTab = new javax.swing.JPanel();
        radioButton5d = new javax.swing.JRadioButton(aud5);
        radioButton10d = new javax.swing.JRadioButton(aud10);
        radioButton20d = new javax.swing.JRadioButton(aud20);
        radioButton50d = new javax.swing.JRadioButton(aud50);
        radioButton100d = new javax.swing.JRadioButton(aud100);
        banknotePicture = new javax.swing.JLabel(createImageIcon(""));
        audCoin = new javax.swing.JLabel();
        radioButton5c = new javax.swing.JRadioButton(aud5c);
        radioButton10c = new javax.swing.JRadioButton(aud10c);
        radioButton20c = new javax.swing.JRadioButton(aud20c);
        radioButton50c = new javax.swing.JRadioButton(aud50c);
        radioButton1d = new javax.swing.JRadioButton(aud1);
        radioButton2d = new javax.swing.JRadioButton(aud2);
        coinPicture = new javax.swing.JLabel();
        audBanknote = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userTab = new javax.swing.JPanel();
        officialUserLabel = new javax.swing.JLabel();
        auLabel = new javax.swing.JLabel();
        naLabel = new javax.swing.JLabel();
        autLabel = new javax.swing.JLabel();
        ascLabel = new javax.swing.JLabel();
        aatLabel = new javax.swing.JLabel();
        chLabel = new javax.swing.JLabel();
        coLabel = new javax.swing.JLabel();
        acsLabel = new javax.swing.JLabel();
        ahiLabel = new javax.swing.JLabel();
        noLabel = new javax.swing.JLabel();
        unofficialUserLabel = new javax.swing.JLabel();
        kiLabel = new javax.swing.JLabel();
        tuLabel = new javax.swing.JLabel();
        ziLabel = new javax.swing.JLabel();
        otherTab = new javax.swing.JPanel();
        isoLabel = new javax.swing.JLabel();
        isoLabel2 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        bankLabel2 = new javax.swing.JLabel();
        pegLabel = new javax.swing.JLabel();
        pegLabel2 = new javax.swing.JLabel();
        inflationLabel = new javax.swing.JLabel();
        inflationLabel2 = new javax.swing.JLabel();
        printerLabel = new javax.swing.JLabel();
        printerLabel2 = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        subunitLabel2 = new javax.swing.JLabel();
        audInfoTitle = new javax.swing.JLabel();

        setTitle("Australian Dollar");

        audButtonGroup.add(radioButton5d);
        radioButton5d.setText("$5");
        radioButton5d.setActionCommand(aud5);
        radioButton5d.addActionListener(this);

        audButtonGroup.add(radioButton10d);
        radioButton10d.setText("$10");
        radioButton10d.setActionCommand(aud10);
        radioButton10d.addActionListener(this);

        audButtonGroup.add(radioButton20d);
        radioButton20d.setText("$20");
        radioButton20d.setActionCommand(aud20);
        radioButton20d.addActionListener(this);

        audButtonGroup.add(radioButton50d);
        radioButton50d.setText("$50");
        radioButton50d.setActionCommand(aud50);
        radioButton50d.addActionListener(this);

        audButtonGroup.add(radioButton100d);
        radioButton100d.setText("$100");
        radioButton100d.setActionCommand(aud100);
        radioButton100d.addActionListener(this);

        banknotePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        audCoin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        audCoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        audCoin.setText("Coin");

        audButtonGroup.add(radioButton5c);
        radioButton5c.setText("5¢");
        radioButton5c.setActionCommand(aud5c);
        radioButton5c.addActionListener(this);

        audButtonGroup.add(radioButton10c);
        radioButton10c.setText("10¢");
        radioButton10c.setActionCommand(aud10c);
        radioButton10c.addActionListener(this);

        audButtonGroup.add(radioButton20c);
        radioButton20c.setText("20¢");
        radioButton20c.setActionCommand(aud20c);
        radioButton20c.addActionListener(this);

        audButtonGroup.add(radioButton50c);
        radioButton50c.setText("50¢");
        radioButton50c.setActionCommand(aud50c);
        radioButton50c.addActionListener(this);

        audButtonGroup.add(radioButton1d);
        radioButton1d.setText("$1");
        radioButton1d.setActionCommand(aud1);
        radioButton1d.addActionListener(this);

        audButtonGroup.add(radioButton2d);
        radioButton2d.setText("$2");
        radioButton2d.setActionCommand(aud2);
        radioButton2d.addActionListener(this);

        coinPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        audBanknote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        audBanknote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        audBanknote.setText("Banknote");

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoTabLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(radioButton5c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton10c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton20c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton50c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton1d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton2d)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(infoTabLayout.createSequentialGroup()
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(infoTabLayout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addComponent(radioButton5d)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton10d)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton20d)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton50d)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton100d))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoTabLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(audCoin, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(infoTabLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(audBanknote, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(audBanknote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5d)
                    .addComponent(radioButton10d)
                    .addComponent(radioButton20d)
                    .addComponent(radioButton50d)
                    .addComponent(radioButton100d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(audCoin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5c)
                    .addComponent(radioButton10c)
                    .addComponent(radioButton20c)
                    .addComponent(radioButton50c)
                    .addComponent(radioButton1d)
                    .addComponent(radioButton2d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        audInfoTab.addTab("Info", infoTab);

        officialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officialUserLabel.setText("Official Users");

        auLabel.setText("Australia");

        naLabel.setText("Nauru");

        autLabel.setText("Australian Territories");

        ascLabel.setText("Ashmore and Cartier Islands");

        aatLabel.setText("Australian Antarctic Territory");

        chLabel.setText("Christmas Island");

        coLabel.setText("Cocos (Keeling) Islands");

        acsLabel.setText("Australia Coral Sea Islands");

        ahiLabel.setText("Australia Heard Island and McDonald Islands");

        noLabel.setText("Norfolk Island");

        unofficialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unofficialUserLabel.setText("Unofficial Users");

        kiLabel.setText("Kiribati");

        tuLabel.setText("Tuvalu");

        ziLabel.setText("Zimbabwe");

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acsLabel)
                    .addComponent(ziLabel)
                    .addComponent(tuLabel)
                    .addComponent(kiLabel)
                    .addComponent(officialUserLabel)
                    .addComponent(unofficialUserLabel)
                    .addComponent(autLabel)
                    .addComponent(coLabel)
                    .addComponent(chLabel)
                    .addComponent(aatLabel)
                    .addGroup(userTabLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ascLabel)
                            .addComponent(naLabel)
                            .addComponent(auLabel)
                            .addComponent(noLabel)
                            .addComponent(ahiLabel))))
                .addGap(285, 285, 285))
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(officialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(auLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ascLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ahiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noLabel)
                .addGap(18, 18, 18)
                .addComponent(unofficialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ziLabel)
                .addGap(223, 223, 223))
        );

        audInfoTab.addTab("Users", userTab);

        isoLabel.setText("ISO 4217 Code:");

        isoLabel2.setText(" AUD");

        bankLabel.setText("Central Bank:");

        bankLabel2.setText("Reserve Bank of Australia");

        pegLabel.setText("Pegged by:");

        pegLabel2.setText("Tuvaluan dollar and Kiribati dollar at par");

        inflationLabel.setText("Inflation:");

        inflationLabel2.setText("2.2% (Australia only)");

        printerLabel.setText("Printer:");

        printerLabel2.setText("Note Printing Australia");

        subunitLabel.setText("Subunit:");

        subunitLabel2.setText("1/100 (cent)");

        javax.swing.GroupLayout otherTabLayout = new javax.swing.GroupLayout(otherTab);
        otherTab.setLayout(otherTabLayout);
        otherTabLayout.setHorizontalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(subunitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subunitLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(pegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(printerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printerLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(isoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(bankLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(inflationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inflationLabel2)))
                .addGap(229, 229, 229))
        );
        otherTabLayout.setVerticalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isoLabel)
                    .addComponent(isoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankLabel)
                    .addComponent(bankLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pegLabel)
                    .addComponent(pegLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subunitLabel)
                    .addComponent(subunitLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationLabel)
                    .addComponent(inflationLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printerLabel)
                    .addComponent(printerLabel2))
                .addGap(424, 424, 424))
        );

        audInfoTab.addTab("Other", otherTab);

        audInfoTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        audInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        audInfoTitle.setText("Australian Dollar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(audInfoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(audInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(audInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(audInfoTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AUDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AUDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AUDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AUDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AUDinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aatLabel;
    private javax.swing.JLabel acsLabel;
    private javax.swing.JLabel ahiLabel;
    private javax.swing.JLabel ascLabel;
    private javax.swing.JLabel auLabel;
    private javax.swing.JLabel audBanknote;
    private javax.swing.ButtonGroup audButtonGroup;
    private javax.swing.JLabel audCoin;
    private javax.swing.JTabbedPane audInfoTab;
    private javax.swing.JLabel audInfoTitle;
    private javax.swing.JLabel autLabel;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JLabel banknotePicture;
    private javax.swing.JLabel chLabel;
    private javax.swing.JLabel coLabel;
    private javax.swing.JLabel coinPicture;
    private javax.swing.JLabel inflationLabel;
    private javax.swing.JLabel inflationLabel2;
    private javax.swing.JPanel infoTab;
    private javax.swing.JLabel isoLabel;
    private javax.swing.JLabel isoLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kiLabel;
    private javax.swing.JLabel naLabel;
    private javax.swing.JLabel noLabel;
    private javax.swing.JLabel officialUserLabel;
    private javax.swing.JPanel otherTab;
    private javax.swing.JLabel pegLabel;
    private javax.swing.JLabel pegLabel2;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JLabel printerLabel2;
    private javax.swing.JRadioButton radioButton100d;
    private javax.swing.JRadioButton radioButton10c;
    private javax.swing.JRadioButton radioButton10d;
    private javax.swing.JRadioButton radioButton1d;
    private javax.swing.JRadioButton radioButton20c;
    private javax.swing.JRadioButton radioButton20d;
    private javax.swing.JRadioButton radioButton2d;
    private javax.swing.JRadioButton radioButton50c;
    private javax.swing.JRadioButton radioButton50d;
    private javax.swing.JRadioButton radioButton5c;
    private javax.swing.JRadioButton radioButton5d;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JLabel subunitLabel2;
    private javax.swing.JLabel tuLabel;
    private javax.swing.JLabel unofficialUserLabel;
    private javax.swing.JPanel userTab;
    private javax.swing.JLabel ziLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (radioButton5d.isSelected() ||
                radioButton10d.isSelected() ||
                radioButton20d.isSelected() ||
                radioButton50d.isSelected() ||
                radioButton100d.isSelected()) {
        banknotePicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        } else {
            coinPicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        }
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = AUDinfo.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(JFrame, "File Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
}

