/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adam.convertcurrency;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Bodie
 */
public class CADinfo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form CADinfo
     */
    static String cad5c = "CAD5c";
    static String cad10c = "CAD10c";
    static String cad25c = "CAD25c";
    static String cad50c = "CAD50c";
    static String cad1 = "CAD$1";
    static String cad2 = "CAD$2";
    static String cad5 = "CAD$5";
    static String cad10 = "CAD$10";
    static String cad20 = "CAD$20";
    static String cad50 = "CAD$50";
    static String cad100 = "CAD$100";
    private static Component JFrame;
    
    public CADinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadButtonGroup = new javax.swing.ButtonGroup();
        cadInfoTab = new javax.swing.JTabbedPane();
        infoTab = new javax.swing.JPanel();
        radioButton5d = new javax.swing.JRadioButton(cad5);
        radioButton10d = new javax.swing.JRadioButton(cad10);
        radioButton20d = new javax.swing.JRadioButton(cad20);
        radioButton50d = new javax.swing.JRadioButton(cad50);
        radioButton100d = new javax.swing.JRadioButton(cad100);
        banknotePicture = new javax.swing.JLabel(createImageIcon(""));
        jSeparator1 = new javax.swing.JSeparator();
        coin = new javax.swing.JLabel();
        radioButton5c = new javax.swing.JRadioButton(cad5c);
        radioButton10c = new javax.swing.JRadioButton(cad10c);
        radioButton25c = new javax.swing.JRadioButton(cad25c);
        radioButton50c = new javax.swing.JRadioButton(cad50c);
        radioButton1d = new javax.swing.JRadioButton(cad1);
        radioButton2d = new javax.swing.JRadioButton(cad2);
        coinPicture = new javax.swing.JLabel();
        banknote = new javax.swing.JLabel();
        userTab = new javax.swing.JPanel();
        officialUserLabel = new javax.swing.JLabel();
        unofficialUserLabel = new javax.swing.JLabel();
        caLabel = new javax.swing.JLabel();
        spmLabel = new javax.swing.JLabel();
        otherTab = new javax.swing.JPanel();
        isoLabel = new javax.swing.JLabel();
        isoLabel2 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        bankLabel2 = new javax.swing.JLabel();
        inflationLabel = new javax.swing.JLabel();
        inflationLabel2 = new javax.swing.JLabel();
        printerLabel = new javax.swing.JLabel();
        printerLabel2 = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        subunitLabel2 = new javax.swing.JLabel();
        cadInfoTitle = new javax.swing.JLabel();

        setTitle("Canadian Dollar");

        cadButtonGroup.add(radioButton5d);
        radioButton5d.setText("$5");
        radioButton5d.setActionCommand(cad5);
        radioButton5d.addActionListener(this);

        cadButtonGroup.add(radioButton10d);
        radioButton10d.setText("$10");
        radioButton10d.setActionCommand(cad10);
        radioButton10d.addActionListener(this);

        cadButtonGroup.add(radioButton20d);
        radioButton20d.setText("$20");
        radioButton20d.setActionCommand(cad20);
        radioButton20d.addActionListener(this);

        cadButtonGroup.add(radioButton50d);
        radioButton50d.setText("$50");
        radioButton50d.setActionCommand(cad50);
        radioButton50d.addActionListener(this);

        cadButtonGroup.add(radioButton100d);
        radioButton100d.setText("$100");
        radioButton100d.setActionCommand(cad100);
        radioButton100d.addActionListener(this);

        banknotePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin.setText("Coin");

        cadButtonGroup.add(radioButton5c);
        radioButton5c.setText("5¢");
        radioButton5c.setActionCommand(cad5c);
        radioButton5c.addActionListener(this);

        cadButtonGroup.add(radioButton10c);
        radioButton10c.setText("10¢");
        radioButton10c.setActionCommand(cad10c);
        radioButton10c.addActionListener(this);

        cadButtonGroup.add(radioButton25c);
        radioButton25c.setText("25¢");
        radioButton25c.setActionCommand(cad25c);
        radioButton25c.addActionListener(this);

        cadButtonGroup.add(radioButton50c);
        radioButton50c.setText("50¢");
        radioButton50c.setActionCommand(cad50c);
        radioButton50c.addActionListener(this);

        cadButtonGroup.add(radioButton1d);
        radioButton1d.setText("$1");
        radioButton1d.setActionCommand(cad1);
        radioButton1d.addActionListener(this);

        cadButtonGroup.add(radioButton2d);
        radioButton2d.setText("$2");
        radioButton2d.setActionCommand(cad2);
        radioButton2d.addActionListener(this);

        coinPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        banknote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banknote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banknote.setText("Banknote");

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(radioButton5c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton10c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton25c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton50c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton1d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton2d))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(radioButton5d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton10d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton20d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton50d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton100d))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(banknote, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coin, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78))
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banknote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5d)
                    .addComponent(radioButton10d)
                    .addComponent(radioButton20d)
                    .addComponent(radioButton50d)
                    .addComponent(radioButton100d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5c)
                    .addComponent(radioButton10c)
                    .addComponent(radioButton25c)
                    .addComponent(radioButton50c)
                    .addComponent(radioButton1d)
                    .addComponent(radioButton2d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        cadInfoTab.addTab("Info", infoTab);

        officialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officialUserLabel.setText("Official Users");

        unofficialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unofficialUserLabel.setText("Unofficial Users");

        caLabel.setText("Canada");

        spmLabel.setText("Saint Pierre and Miquelon (France)");

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userTabLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spmLabel))
                    .addComponent(unofficialUserLabel)
                    .addComponent(caLabel)
                    .addComponent(officialUserLabel))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(officialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unofficialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spmLabel)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        cadInfoTab.addTab("Users", userTab);

        isoLabel.setText("ISO 4217 Code:");

        isoLabel2.setText("CAD");

        bankLabel.setText("Central Bank:");

        bankLabel2.setText("Bank of Canada");

        inflationLabel.setText("Inflation:");

        inflationLabel2.setText("1.6%");

        printerLabel.setText("Printer:");

        printerLabel2.setText("Canadian Bank Note Company");

        subunitLabel.setText("Subunit:");

        subunitLabel2.setText("1/100 (cent)");

        javax.swing.GroupLayout otherTabLayout = new javax.swing.GroupLayout(otherTab);
        otherTab.setLayout(otherTabLayout);
        otherTabLayout.setHorizontalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(subunitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subunitLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(printerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printerLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(inflationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inflationLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(bankLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(isoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoLabel2)))
                .addGap(288, 288, 288))
        );
        otherTabLayout.setVerticalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isoLabel)
                    .addComponent(isoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankLabel)
                    .addComponent(bankLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subunitLabel)
                    .addComponent(subunitLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationLabel)
                    .addComponent(inflationLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printerLabel)
                    .addComponent(printerLabel2))
                .addGap(424, 424, 424))
        );

        cadInfoTab.addTab("Other", otherTab);

        cadInfoTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadInfoTitle.setText("Canadian Dollar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadInfoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(cadInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadInfoTitle)
                .addGap(18, 18, 18)
                .addComponent(cadInfoTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CADinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CADinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CADinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CADinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CADinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JLabel banknote;
    private javax.swing.JLabel banknotePicture;
    private javax.swing.JLabel caLabel;
    private javax.swing.ButtonGroup cadButtonGroup;
    private javax.swing.JTabbedPane cadInfoTab;
    private javax.swing.JLabel cadInfoTitle;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinPicture;
    private javax.swing.JLabel inflationLabel;
    private javax.swing.JLabel inflationLabel2;
    private javax.swing.JPanel infoTab;
    private javax.swing.JLabel isoLabel;
    private javax.swing.JLabel isoLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel officialUserLabel;
    private javax.swing.JPanel otherTab;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JLabel printerLabel2;
    private javax.swing.JRadioButton radioButton100d;
    private javax.swing.JRadioButton radioButton10c;
    private javax.swing.JRadioButton radioButton10d;
    private javax.swing.JRadioButton radioButton1d;
    private javax.swing.JRadioButton radioButton20d;
    private javax.swing.JRadioButton radioButton25c;
    private javax.swing.JRadioButton radioButton2d;
    private javax.swing.JRadioButton radioButton50c;
    private javax.swing.JRadioButton radioButton50d;
    private javax.swing.JRadioButton radioButton5c;
    private javax.swing.JRadioButton radioButton5d;
    private javax.swing.JLabel spmLabel;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JLabel subunitLabel2;
    private javax.swing.JLabel unofficialUserLabel;
    private javax.swing.JPanel userTab;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (radioButton5d.isSelected() ||
                radioButton10d.isSelected() ||
                radioButton20d.isSelected() ||
                radioButton50d.isSelected() ||
                radioButton100d.isSelected()) {
        banknotePicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        } else {
            coinPicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        }
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = CADinfo.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(JFrame, "File Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    } 
}
