/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adam.convertcurrency;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Bodie
 */
public class EURinfo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form EURinfo
     */
    static String eur1c = "EUR1c";
    static String eur2c = "EUR2c";
    static String eur5c = "EUR5c";
    static String eur10c = "EUR10c";
    static String eur20c = "EUR20c";
    static String eur50c = "EUR50c";
    static String eur1 = "EUR1";
    static String eur2 = "EUR2";
    static String eur5 = "EUR5";
    static String eur10 = "EUR10";
    static String eur20 = "EUR20";
    static String eur50 = "EUR50";
    static String eur100 = "EUR100";
    static String eur200 = "EUR200";
    static String eur500 = "EUR500";
    private static Component JFrame;
    
    public EURinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eurButtonGroup = new javax.swing.ButtonGroup();
        eurInfoTab = new javax.swing.JTabbedPane();
        infoTab = new javax.swing.JPanel();
        radioButton5 = new javax.swing.JRadioButton(eur5);
        radioButton10 = new javax.swing.JRadioButton(eur10);
        radioButton20 = new javax.swing.JRadioButton(eur20);
        radioButton50 = new javax.swing.JRadioButton(eur50);
        radioButton100 = new javax.swing.JRadioButton(eur100);
        radioButton200 = new javax.swing.JRadioButton(eur200);
        radioButton500 = new javax.swing.JRadioButton(eur500);
        banknotePicture = new javax.swing.JLabel(createImageIcon(""));
        jSeparator1 = new javax.swing.JSeparator();
        coin = new javax.swing.JLabel();
        radioButton1c = new javax.swing.JRadioButton(eur1c);
        radioButton2c = new javax.swing.JRadioButton(eur2c);
        radioButton5c = new javax.swing.JRadioButton(eur5c);
        radioButton10c = new javax.swing.JRadioButton(eur10c);
        radioButton20c = new javax.swing.JRadioButton(eur20c);
        radioButton50c = new javax.swing.JRadioButton(eur50c);
        radioButton1 = new javax.swing.JRadioButton(eur1);
        radioButton2 = new javax.swing.JRadioButton(eur2);
        coinPicture = new javax.swing.JLabel();
        banknote = new javax.swing.JLabel();
        userTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        officialUserLabel = new javax.swing.JLabel();
        terLabel = new javax.swing.JLabel();
        unofficialUserLabel = new javax.swing.JLabel();
        anLabel = new javax.swing.JLabel();
        auLabel = new javax.swing.JLabel();
        beLabel = new javax.swing.JLabel();
        cyLabel = new javax.swing.JLabel();
        esLabel = new javax.swing.JLabel();
        fiLabel = new javax.swing.JLabel();
        frLabel = new javax.swing.JLabel();
        geLabel = new javax.swing.JLabel();
        grLabel = new javax.swing.JLabel();
        irLabel = new javax.swing.JLabel();
        itLabel = new javax.swing.JLabel();
        laLabel = new javax.swing.JLabel();
        luLabel = new javax.swing.JLabel();
        maLabel = new javax.swing.JLabel();
        moLabel = new javax.swing.JLabel();
        neLabel = new javax.swing.JLabel();
        poLabel = new javax.swing.JLabel();
        smLabel = new javax.swing.JLabel();
        skLabel = new javax.swing.JLabel();
        snLabel = new javax.swing.JLabel();
        spLabel = new javax.swing.JLabel();
        vcLabel = new javax.swing.JLabel();
        akLabel = new javax.swing.JLabel();
        clLabel = new javax.swing.JLabel();
        fsLabel = new javax.swing.JLabel();
        sbLabel = new javax.swing.JLabel();
        spmLabel = new javax.swing.JLabel();
        ncLabel = new javax.swing.JLabel();
        koLabel = new javax.swing.JLabel();
        mtLabel = new javax.swing.JLabel();
        ziLabel = new javax.swing.JLabel();
        otherTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        isoLabel = new javax.swing.JLabel();
        isoLabel2 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        bankLabel2 = new javax.swing.JLabel();
        pegLabel = new javax.swing.JLabel();
        pegLabel1 = new javax.swing.JLabel();
        pegLabel2 = new javax.swing.JLabel();
        pegLabel3 = new javax.swing.JLabel();
        pegLabel4 = new javax.swing.JLabel();
        pegLabel5 = new javax.swing.JLabel();
        pegLabel6 = new javax.swing.JLabel();
        pegLabel7 = new javax.swing.JLabel();
        pegLabel8 = new javax.swing.JLabel();
        pegLabel9 = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        subunitLabel2 = new javax.swing.JLabel();
        inflationLabel = new javax.swing.JLabel();
        inflationLabel2 = new javax.swing.JLabel();
        printerLabel = new javax.swing.JLabel();
        printerLabel1 = new javax.swing.JLabel();
        printerLabel2 = new javax.swing.JLabel();
        printerLabel3 = new javax.swing.JLabel();
        printerLabel4 = new javax.swing.JLabel();
        printerLabel5 = new javax.swing.JLabel();
        printerLabel6 = new javax.swing.JLabel();
        printerLabel7 = new javax.swing.JLabel();
        printerLabel8 = new javax.swing.JLabel();
        printerLabel9 = new javax.swing.JLabel();
        printerLabel10 = new javax.swing.JLabel();
        printerLabel11 = new javax.swing.JLabel();
        printerLabel12 = new javax.swing.JLabel();
        printerLabel13 = new javax.swing.JLabel();
        printerLabel14 = new javax.swing.JLabel();
        eurInfoTitle = new javax.swing.JLabel();

        setTitle("Euro");

        eurButtonGroup.add(radioButton5);
        radioButton5.setText("€5");
        radioButton5.setActionCommand(eur5);
        radioButton5.addActionListener(this);

        eurButtonGroup.add(radioButton10);
        radioButton10.setText("€10");
        radioButton10.setActionCommand(eur10);
        radioButton10.addActionListener(this);

        eurButtonGroup.add(radioButton20);
        radioButton20.setText("€20");
        radioButton20.setActionCommand(eur20);
        radioButton20.addActionListener(this);

        eurButtonGroup.add(radioButton50);
        radioButton50.setText("€50");
        radioButton50.setActionCommand(eur50);
        radioButton50.addActionListener(this);

        eurButtonGroup.add(radioButton100);
        radioButton100.setText("€100");
        radioButton100.setActionCommand(eur100);
        radioButton100.addActionListener(this);

        eurButtonGroup.add(radioButton200);
        radioButton200.setText("€200");
        radioButton200.setActionCommand(eur200);
        radioButton200.addActionListener(this);

        eurButtonGroup.add(radioButton500);
        radioButton500.setText("€500");
        radioButton500.setActionCommand(eur500);
        radioButton500.addActionListener(this);

        banknotePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin.setText("Coin");

        eurButtonGroup.add(radioButton1c);
        radioButton1c.setText("1c");
        radioButton1c.setActionCommand(eur1c);
        radioButton1c.addActionListener(this);

        eurButtonGroup.add(radioButton2c);
        radioButton2c.setText("2c");
        radioButton2c.setActionCommand(eur2c);
        radioButton2c.addActionListener(this);

        eurButtonGroup.add(radioButton5c);
        radioButton5c.setText("5c");
        radioButton5c.setActionCommand(eur5c);
        radioButton5c.addActionListener(this);

        eurButtonGroup.add(radioButton10c);
        radioButton10c.setText("10c");
        radioButton10c.setActionCommand(eur10c);
        radioButton10c.addActionListener(this);

        eurButtonGroup.add(radioButton20c);
        radioButton20c.setText("20c");
        radioButton20c.setActionCommand(eur20c);
        radioButton20c.addActionListener(this);

        eurButtonGroup.add(radioButton50c);
        radioButton50c.setText("50c");
        radioButton50c.setActionCommand(eur50c);
        radioButton50c.addActionListener(this);

        eurButtonGroup.add(radioButton1);
        radioButton1.setText("€1");
        radioButton1.setActionCommand(eur1);
        radioButton1.addActionListener(this);

        eurButtonGroup.add(radioButton2);
        radioButton2.setText("€2");
        radioButton2.setActionCommand(eur2);
        radioButton2.addActionListener(this);

        coinPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        banknote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banknote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banknote.setText("Banknote");

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(radioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton200)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton500))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(radioButton1c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton2c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton5c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton10c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton20c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton50c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton2))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(banknote, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coin, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banknote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5)
                    .addComponent(radioButton10)
                    .addComponent(radioButton20)
                    .addComponent(radioButton50)
                    .addComponent(radioButton100)
                    .addComponent(radioButton200)
                    .addComponent(radioButton500))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5c)
                    .addComponent(radioButton10c)
                    .addComponent(radioButton20c)
                    .addComponent(radioButton50c)
                    .addComponent(radioButton1)
                    .addComponent(radioButton2)
                    .addComponent(radioButton2c)
                    .addComponent(radioButton1c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        eurInfoTab.addTab("Info", infoTab);

        officialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officialUserLabel.setText("Official Users");

        terLabel.setText("Territories");

        unofficialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unofficialUserLabel.setText("Unofficial Users");

        anLabel.setText("Andorra");

        auLabel.setText("Austria");

        beLabel.setText("Belgium");

        cyLabel.setText("Cyprus");

        esLabel.setText("Estonia");

        fiLabel.setText("Finland");

        frLabel.setText("France");

        geLabel.setText("Germany");

        grLabel.setText("Greece");

        irLabel.setText("Ireland");

        itLabel.setText("Italy");

        laLabel.setText("Latvia");

        luLabel.setText("Luxembourg");

        maLabel.setText("Malta");

        moLabel.setText("Monaco");

        neLabel.setText("The Netherlands");

        poLabel.setText("Portugal");

        smLabel.setText("San Marino");

        skLabel.setText("Slovakia");

        snLabel.setText("Slovenia");

        spLabel.setText("Spain");

        vcLabel.setText("Vatican City");

        akLabel.setText("Akrotiri and Dhekelia (United Kingdom)");

        clLabel.setText("Clipperton Island (France)");

        fsLabel.setText("French Southern and Antarctic Lands (France)");

        sbLabel.setText("Saint Barthélemy (France)");

        spmLabel.setText("Saint Pierre and Miquelon (France)");

        ncLabel.setText("Northern Cyprus");

        koLabel.setText("Kosovo");

        mtLabel.setText("Montenegro");

        ziLabel.setText("Zimbabwe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officialUserLabel)
                    .addComponent(unofficialUserLabel)
                    .addComponent(terLabel)
                    .addComponent(vcLabel)
                    .addComponent(spLabel)
                    .addComponent(snLabel)
                    .addComponent(skLabel)
                    .addComponent(smLabel)
                    .addComponent(poLabel)
                    .addComponent(neLabel)
                    .addComponent(moLabel)
                    .addComponent(maLabel)
                    .addComponent(luLabel)
                    .addComponent(laLabel)
                    .addComponent(itLabel)
                    .addComponent(irLabel)
                    .addComponent(grLabel)
                    .addComponent(geLabel)
                    .addComponent(frLabel)
                    .addComponent(fiLabel)
                    .addComponent(esLabel)
                    .addComponent(anLabel)
                    .addComponent(cyLabel)
                    .addComponent(auLabel)
                    .addComponent(beLabel)
                    .addComponent(clLabel)
                    .addComponent(akLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ziLabel)
                            .addComponent(mtLabel)
                            .addComponent(koLabel)
                            .addComponent(ncLabel)
                            .addComponent(spmLabel)
                            .addComponent(sbLabel)
                            .addComponent(fsLabel))))
                .addGap(172, 172, 172))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(officialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(auLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(esLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(irLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vcLabel)
                .addGap(18, 18, 18)
                .addComponent(terLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unofficialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ncLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(koLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ziLabel)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        eurInfoTab.addTab("Users", userTab);

        isoLabel.setText("ISO 4217 Code:");

        isoLabel2.setText("EUR");

        bankLabel.setText("Central Bank:");

        bankLabel2.setText("European Central Bank");

        pegLabel.setText("Pegged by: ");

        pegLabel1.setText("Bosnia and Herzegovina convertible mark");

        pegLabel2.setText("Bulgarian lev");

        pegLabel3.setText("Cape Verdean escudo");

        pegLabel4.setText("Central African CFA franc");

        pegLabel5.setText("CFP franc");

        pegLabel6.setText("Comorian franc");

        pegLabel7.setText("Danish krone (±2.25%)");

        pegLabel8.setText("Lithuanian litas");

        pegLabel9.setText("West African CFA franc");

        subunitLabel.setText("Subunit:");

        subunitLabel2.setText("1/100 (cent)");

        inflationLabel.setText("Inflation:");

        inflationLabel2.setText("0.8%");

        printerLabel.setText("Printer:");

        printerLabel1.setText("Istituto Poligrafico e Zecca dello Stato");

        printerLabel2.setText("Banco de Portugal");

        printerLabel3.setText("Bank of Greece");

        printerLabel4.setText("Banque de France");

        printerLabel5.setText("Bundesdruckerei");

        printerLabel6.setText("Central Bank and Financial Services Authority of Ireland");

        printerLabel7.setText("De La Rue");

        printerLabel8.setText("Fábrica Nacional de Moneda y Timbre");

        printerLabel9.setText("François-Charles Oberthur");

        printerLabel10.setText("Giesecke & Devrient");

        printerLabel11.setText("Royal Joh. Enschedé");

        printerLabel12.setText("National Bank of Belgium");

        printerLabel13.setText("Oesterreichische Banknoten- und Sicherheitsdruck GmbH");

        printerLabel14.setText("Setec Oy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(isoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bankLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pegLabel5)
                            .addComponent(pegLabel8)
                            .addComponent(pegLabel9)
                            .addComponent(pegLabel2)
                            .addComponent(pegLabel1)
                            .addComponent(pegLabel3)
                            .addComponent(pegLabel4)
                            .addComponent(pegLabel6)
                            .addComponent(pegLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(printerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printerLabel2)
                            .addComponent(printerLabel1)
                            .addComponent(printerLabel4)
                            .addComponent(printerLabel5)
                            .addComponent(printerLabel6)
                            .addComponent(printerLabel7)
                            .addComponent(printerLabel8)
                            .addComponent(printerLabel3)
                            .addComponent(printerLabel9)
                            .addComponent(printerLabel10)
                            .addComponent(printerLabel11)
                            .addComponent(printerLabel12)
                            .addComponent(printerLabel13)
                            .addComponent(printerLabel14)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inflationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inflationLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(subunitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subunitLabel2)))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isoLabel)
                    .addComponent(isoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankLabel)
                    .addComponent(bankLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pegLabel)
                    .addComponent(pegLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subunitLabel)
                    .addComponent(subunitLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationLabel)
                    .addComponent(inflationLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printerLabel)
                    .addComponent(printerLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel14)
                .addGap(44, 44, 44))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout otherTabLayout = new javax.swing.GroupLayout(otherTab);
        otherTab.setLayout(otherTabLayout);
        otherTabLayout.setHorizontalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        otherTabLayout.setVerticalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        eurInfoTab.addTab("Other", otherTab);

        eurInfoTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eurInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eurInfoTitle.setText("Euro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eurInfoTab, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(eurInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eurInfoTitle)
                .addGap(18, 18, 18)
                .addComponent(eurInfoTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EURinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EURinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EURinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EURinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EURinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akLabel;
    private javax.swing.JLabel anLabel;
    private javax.swing.JLabel auLabel;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JLabel banknote;
    private javax.swing.JLabel banknotePicture;
    private javax.swing.JLabel beLabel;
    private javax.swing.JLabel clLabel;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinPicture;
    private javax.swing.JLabel cyLabel;
    private javax.swing.JLabel esLabel;
    private javax.swing.ButtonGroup eurButtonGroup;
    private javax.swing.JTabbedPane eurInfoTab;
    private javax.swing.JLabel eurInfoTitle;
    private javax.swing.JLabel fiLabel;
    private javax.swing.JLabel frLabel;
    private javax.swing.JLabel fsLabel;
    private javax.swing.JLabel geLabel;
    private javax.swing.JLabel grLabel;
    private javax.swing.JLabel inflationLabel;
    private javax.swing.JLabel inflationLabel2;
    private javax.swing.JPanel infoTab;
    private javax.swing.JLabel irLabel;
    private javax.swing.JLabel isoLabel;
    private javax.swing.JLabel isoLabel2;
    private javax.swing.JLabel itLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel koLabel;
    private javax.swing.JLabel laLabel;
    private javax.swing.JLabel luLabel;
    private javax.swing.JLabel maLabel;
    private javax.swing.JLabel moLabel;
    private javax.swing.JLabel mtLabel;
    private javax.swing.JLabel ncLabel;
    private javax.swing.JLabel neLabel;
    private javax.swing.JLabel officialUserLabel;
    private javax.swing.JPanel otherTab;
    private javax.swing.JLabel pegLabel;
    private javax.swing.JLabel pegLabel1;
    private javax.swing.JLabel pegLabel2;
    private javax.swing.JLabel pegLabel3;
    private javax.swing.JLabel pegLabel4;
    private javax.swing.JLabel pegLabel5;
    private javax.swing.JLabel pegLabel6;
    private javax.swing.JLabel pegLabel7;
    private javax.swing.JLabel pegLabel8;
    private javax.swing.JLabel pegLabel9;
    private javax.swing.JLabel poLabel;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JLabel printerLabel1;
    private javax.swing.JLabel printerLabel10;
    private javax.swing.JLabel printerLabel11;
    private javax.swing.JLabel printerLabel12;
    private javax.swing.JLabel printerLabel13;
    private javax.swing.JLabel printerLabel14;
    private javax.swing.JLabel printerLabel2;
    private javax.swing.JLabel printerLabel3;
    private javax.swing.JLabel printerLabel4;
    private javax.swing.JLabel printerLabel5;
    private javax.swing.JLabel printerLabel6;
    private javax.swing.JLabel printerLabel7;
    private javax.swing.JLabel printerLabel8;
    private javax.swing.JLabel printerLabel9;
    private javax.swing.JRadioButton radioButton1;
    private javax.swing.JRadioButton radioButton10;
    private javax.swing.JRadioButton radioButton100;
    private javax.swing.JRadioButton radioButton10c;
    private javax.swing.JRadioButton radioButton1c;
    private javax.swing.JRadioButton radioButton2;
    private javax.swing.JRadioButton radioButton20;
    private javax.swing.JRadioButton radioButton200;
    private javax.swing.JRadioButton radioButton20c;
    private javax.swing.JRadioButton radioButton2c;
    private javax.swing.JRadioButton radioButton5;
    private javax.swing.JRadioButton radioButton50;
    private javax.swing.JRadioButton radioButton500;
    private javax.swing.JRadioButton radioButton50c;
    private javax.swing.JRadioButton radioButton5c;
    private javax.swing.JLabel sbLabel;
    private javax.swing.JLabel skLabel;
    private javax.swing.JLabel smLabel;
    private javax.swing.JLabel snLabel;
    private javax.swing.JLabel spLabel;
    private javax.swing.JLabel spmLabel;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JLabel subunitLabel2;
    private javax.swing.JLabel terLabel;
    private javax.swing.JLabel unofficialUserLabel;
    private javax.swing.JPanel userTab;
    private javax.swing.JLabel vcLabel;
    private javax.swing.JLabel ziLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (radioButton5.isSelected() ||
                radioButton10.isSelected() ||
                radioButton20.isSelected() ||
                radioButton50.isSelected() ||
                radioButton100.isSelected() ||
                radioButton200.isSelected() ||
                radioButton500.isSelected()) {
        banknotePicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        } else {
            coinPicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        }
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = EURinfo.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(JFrame, "File Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
  
}
