/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adam.convertcurrency;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Bodie
 */
public class GBPinfo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form GBPinfo
     */
    static String gbp1p = "GBP1p";
    static String gbp2p = "GBP2p";
    static String gbp5p = "GBP5p";
    static String gbp10p = "GBP10p";
    static String gbp20p = "GBP20p";
    static String gbp50p = "GBP50p";
    static String gbp1 = "GBP1";
    static String gbp2 = "GBP2";
    static String gbp5 = "GBP5";
    static String gbp10 = "GBP10";
    static String gbp20 = "GBP20";
    static String gbp50 = "GBP50";
    private static Component JFrame;
    
    public GBPinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbpButtonGroup = new javax.swing.ButtonGroup();
        gbpInfoTab = new javax.swing.JTabbedPane();
        infoTab = new javax.swing.JPanel();
        radioButton5 = new javax.swing.JRadioButton(gbp5);
        radioButton10 = new javax.swing.JRadioButton(gbp10);
        radioButton20 = new javax.swing.JRadioButton(gbp20);
        radioButton50 = new javax.swing.JRadioButton(gbp50);
        banknotePicture = new javax.swing.JLabel(createImageIcon(""));
        jSeparator1 = new javax.swing.JSeparator();
        coin = new javax.swing.JLabel();
        radioButton1p = new javax.swing.JRadioButton(gbp1p);
        radioButton2p = new javax.swing.JRadioButton(gbp2p);
        radioButton5p = new javax.swing.JRadioButton(gbp5p);
        radioButton10p = new javax.swing.JRadioButton(gbp10p);
        radioButton20p = new javax.swing.JRadioButton(gbp20p);
        radioButton50p = new javax.swing.JRadioButton(gbp50p);
        radioButton1 = new javax.swing.JRadioButton(gbp1);
        radioButton2 = new javax.swing.JRadioButton(gbp2);
        coinPicture = new javax.swing.JLabel();
        banknote = new javax.swing.JLabel();
        userTab = new javax.swing.JPanel();
        officialUserLabel = new javax.swing.JLabel();
        ukLabel = new javax.swing.JLabel();
        terLabel = new javax.swing.JLabel();
        batLabel = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        faiLabel = new javax.swing.JLabel();
        gibLabel = new javax.swing.JLabel();
        gueLabel = new javax.swing.JLabel();
        islLabel = new javax.swing.JLabel();
        jerLabel = new javax.swing.JLabel();
        shaLabel = new javax.swing.JLabel();
        sgiLabel = new javax.swing.JLabel();
        unofficialUserLabel = new javax.swing.JLabel();
        boLabel = new javax.swing.JLabel();
        maLabel = new javax.swing.JLabel();
        rwLabel = new javax.swing.JLabel();
        slLabel = new javax.swing.JLabel();
        taLabel = new javax.swing.JLabel();
        ugLabel = new javax.swing.JLabel();
        zaLabel = new javax.swing.JLabel();
        ziLabel = new javax.swing.JLabel();
        otherTab = new javax.swing.JPanel();
        isoLabel = new javax.swing.JLabel();
        isoLabel2 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        bankLabel2 = new javax.swing.JLabel();
        pegLabel = new javax.swing.JLabel();
        pegLabel1 = new javax.swing.JLabel();
        pegLabel2 = new javax.swing.JLabel();
        pegLabel3 = new javax.swing.JLabel();
        pegLabel4 = new javax.swing.JLabel();
        pegLabel5 = new javax.swing.JLabel();
        pegLabel6 = new javax.swing.JLabel();
        pegLabel7 = new javax.swing.JLabel();
        pegLabel8 = new javax.swing.JLabel();
        inflationLabel = new javax.swing.JLabel();
        inflationLabel2 = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        subunitLabel2 = new javax.swing.JLabel();
        printerLabel = new javax.swing.JLabel();
        printerLabel1 = new javax.swing.JLabel();
        printerLabel2 = new javax.swing.JLabel();
        printerLabel3 = new javax.swing.JLabel();
        printerLabel4 = new javax.swing.JLabel();
        printerLabel5 = new javax.swing.JLabel();
        printerLabel6 = new javax.swing.JLabel();
        printerLabel7 = new javax.swing.JLabel();
        printerLabel8 = new javax.swing.JLabel();
        printerLabel9 = new javax.swing.JLabel();
        printerLabel10 = new javax.swing.JLabel();
        printerLabel11 = new javax.swing.JLabel();
        gbpInfoTitle = new javax.swing.JLabel();

        setTitle("Pound Sterling");

        gbpButtonGroup.add(radioButton5);
        radioButton5.setText("£5");
        radioButton5.setActionCommand(gbp5);
        radioButton5.addActionListener(this);

        gbpButtonGroup.add(radioButton10);
        radioButton10.setText("£10");
        radioButton10.setActionCommand(gbp10);
        radioButton10.addActionListener(this);

        gbpButtonGroup.add(radioButton20);
        radioButton20.setText("£20");
        radioButton20.setActionCommand(gbp20);
        radioButton20.addActionListener(this);

        gbpButtonGroup.add(radioButton50);
        radioButton50.setText("£50");
        radioButton50.setActionCommand(gbp50);
        radioButton50.addActionListener(this);

        banknotePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin.setText("Coin");

        gbpButtonGroup.add(radioButton1p);
        radioButton1p.setText("1p");
        radioButton1p.setActionCommand(gbp1p);
        radioButton1p.addActionListener(this);

        gbpButtonGroup.add(radioButton2p);
        radioButton2p.setText("2p");
        radioButton2p.setActionCommand(gbp2p);
        radioButton2p.addActionListener(this);

        gbpButtonGroup.add(radioButton5p);
        radioButton5p.setText("5p");
        radioButton5p.setActionCommand(gbp5p);
        radioButton5p.addActionListener(this);

        gbpButtonGroup.add(radioButton10p);
        radioButton10p.setText("10p");
        radioButton10p.setActionCommand(gbp10p);
        radioButton10p.addActionListener(this);

        gbpButtonGroup.add(radioButton20p);
        radioButton20p.setText("20p");
        radioButton20p.setActionCommand(gbp20p);
        radioButton20p.addActionListener(this);

        gbpButtonGroup.add(radioButton50p);
        radioButton50p.setText("50p");
        radioButton50p.setActionCommand(gbp50p);
        radioButton50p.addActionListener(this);

        gbpButtonGroup.add(radioButton1);
        radioButton1.setText("£1");
        radioButton1.setActionCommand(gbp1);
        radioButton1.addActionListener(this);

        gbpButtonGroup.add(radioButton2);
        radioButton2.setText("£2");
        radioButton2.setActionCommand(gbp2);
        radioButton2.addActionListener(this);

        coinPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        banknote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banknote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banknote.setText("Banknote");

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coin, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(infoTabLayout.createSequentialGroup()
                            .addGap(168, 168, 168)
                            .addComponent(radioButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton50))
                        .addGroup(infoTabLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(banknote, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(infoTabLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(radioButton1p)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton2p)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton5p)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton10p)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton20p)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton50p)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButton2))
                        .addGroup(infoTabLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banknote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5)
                    .addComponent(radioButton10)
                    .addComponent(radioButton20)
                    .addComponent(radioButton50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5p)
                    .addComponent(radioButton10p)
                    .addComponent(radioButton20p)
                    .addComponent(radioButton50p)
                    .addComponent(radioButton1)
                    .addComponent(radioButton2)
                    .addComponent(radioButton2p)
                    .addComponent(radioButton1p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        gbpInfoTab.addTab("Info", infoTab);

        officialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officialUserLabel.setText("Official Users");

        ukLabel.setText("United Kingdom");

        terLabel.setText("United Kingdom Territories");

        batLabel.setText("British Antarctic Territory");

        bioLabel.setText("British Indian Ocean");

        faiLabel.setText("Falkland Islands");

        gibLabel.setText("Gibraltar");

        gueLabel.setText("Guernsey");

        islLabel.setText("Isle of Man");

        jerLabel.setText("Jersey");

        shaLabel.setText("Saint Helena, Ascension and Tristan da Cunha");

        sgiLabel.setText("South Georgia and the South Sandwich Islands");

        unofficialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unofficialUserLabel.setText("Unofficial Users");

        boLabel.setText("Botswana");

        maLabel.setText("Malawi");

        rwLabel.setText("Rwanda");

        slLabel.setText("Sierra Leone");

        taLabel.setText("Tanzania");

        ugLabel.setText("Uganda");

        zaLabel.setText("Zambia");

        ziLabel.setText("Zimbabwe");

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userTabLayout.createSequentialGroup()
                        .addGroup(userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(batLabel)
                            .addComponent(bioLabel)
                            .addComponent(faiLabel)
                            .addComponent(gibLabel)
                            .addComponent(gueLabel)
                            .addComponent(islLabel)
                            .addComponent(jerLabel)
                            .addComponent(shaLabel)
                            .addComponent(sgiLabel))
                        .addGap(0, 0, 0))
                    .addGroup(userTabLayout.createSequentialGroup()
                        .addGroup(userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ukLabel)
                            .addComponent(terLabel)
                            .addComponent(officialUserLabel)
                            .addComponent(unofficialUserLabel)
                            .addComponent(ziLabel)
                            .addComponent(zaLabel)
                            .addComponent(ugLabel)
                            .addComponent(taLabel)
                            .addComponent(slLabel)
                            .addComponent(rwLabel)
                            .addComponent(maLabel)
                            .addComponent(boLabel))
                        .addGap(143, 143, 143))))
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(officialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gibLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(islLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sgiLabel)
                .addGap(10, 10, 10)
                .addComponent(unofficialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rwLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ugLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ziLabel)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        gbpInfoTab.addTab("Users", userTab);

        isoLabel.setText("ISO 4217 Code:");

        isoLabel2.setText("GBP");

        bankLabel.setText("Central Bank:");

        bankLabel2.setText("Bank of England");

        pegLabel.setText("Pegged by: ");

        pegLabel1.setText("Falkland Islands pound (at par)");

        pegLabel2.setText("Gibraltar pound (at par)");

        pegLabel3.setText("Saint Helena pound (at par)");

        pegLabel4.setText("Jersey pound (local issue)");

        pegLabel5.setText("Guernsey pound (local issue)");

        pegLabel6.setText("Manx pound (local issue)");

        pegLabel7.setText("Scotland notes (local issue)");

        pegLabel8.setText("Northern Ireland notes (local issue)");

        inflationLabel.setText("Inflation:");

        inflationLabel2.setText("1.5%");

        subunitLabel.setText("Subunit:");

        subunitLabel2.setText("1/100 (penny)");

        printerLabel.setText("Printer:");

        printerLabel1.setText("Bank of England");

        printerLabel2.setText("Bank of Scotland");

        printerLabel3.setText("Royal Bank of Scotland");

        printerLabel4.setText("Clydesdale Bank");

        printerLabel5.setText("Northern Bank");

        printerLabel6.setText("First Trust Bank");

        printerLabel7.setText("Ulster Bank");

        printerLabel8.setText("Bank of Ireland");

        printerLabel9.setText("States of Guernsey");

        printerLabel10.setText("States of Jersey");

        printerLabel11.setText("Isle of Man Government");

        javax.swing.GroupLayout otherTabLayout = new javax.swing.GroupLayout(otherTab);
        otherTab.setLayout(otherTabLayout);
        otherTabLayout.setHorizontalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(printerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printerLabel1))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(isoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(bankLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(subunitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subunitLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(inflationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inflationLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(pegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pegLabel2)
                            .addComponent(pegLabel1)
                            .addComponent(pegLabel3)
                            .addComponent(pegLabel4)
                            .addComponent(pegLabel5)
                            .addComponent(pegLabel6)
                            .addComponent(pegLabel7)
                            .addComponent(pegLabel8)))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printerLabel2)
                            .addComponent(printerLabel3)
                            .addComponent(printerLabel4)
                            .addComponent(printerLabel5)
                            .addComponent(printerLabel6)
                            .addComponent(printerLabel7)
                            .addComponent(printerLabel8)
                            .addComponent(printerLabel9)
                            .addComponent(printerLabel10)
                            .addComponent(printerLabel11))))
                .addGap(242, 242, 242))
        );
        otherTabLayout.setVerticalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isoLabel)
                    .addComponent(isoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankLabel)
                    .addComponent(bankLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pegLabel)
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(pegLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subunitLabel)
                    .addComponent(subunitLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationLabel)
                    .addComponent(inflationLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printerLabel)
                    .addComponent(printerLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printerLabel11)
                .addGap(64, 64, 64))
        );

        gbpInfoTab.addTab("Other", otherTab);

        gbpInfoTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gbpInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gbpInfoTitle.setText("Pound Sterling");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gbpInfoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(gbpInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gbpInfoTitle)
                .addGap(18, 18, 18)
                .addComponent(gbpInfoTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GBPinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GBPinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GBPinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GBPinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GBPinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JLabel banknote;
    private javax.swing.JLabel banknotePicture;
    private javax.swing.JLabel batLabel;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JLabel boLabel;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinPicture;
    private javax.swing.JLabel faiLabel;
    private javax.swing.ButtonGroup gbpButtonGroup;
    private javax.swing.JTabbedPane gbpInfoTab;
    private javax.swing.JLabel gbpInfoTitle;
    private javax.swing.JLabel gibLabel;
    private javax.swing.JLabel gueLabel;
    private javax.swing.JLabel inflationLabel;
    private javax.swing.JLabel inflationLabel2;
    private javax.swing.JPanel infoTab;
    private javax.swing.JLabel islLabel;
    private javax.swing.JLabel isoLabel;
    private javax.swing.JLabel isoLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jerLabel;
    private javax.swing.JLabel maLabel;
    private javax.swing.JLabel officialUserLabel;
    private javax.swing.JPanel otherTab;
    private javax.swing.JLabel pegLabel;
    private javax.swing.JLabel pegLabel1;
    private javax.swing.JLabel pegLabel2;
    private javax.swing.JLabel pegLabel3;
    private javax.swing.JLabel pegLabel4;
    private javax.swing.JLabel pegLabel5;
    private javax.swing.JLabel pegLabel6;
    private javax.swing.JLabel pegLabel7;
    private javax.swing.JLabel pegLabel8;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JLabel printerLabel1;
    private javax.swing.JLabel printerLabel10;
    private javax.swing.JLabel printerLabel11;
    private javax.swing.JLabel printerLabel2;
    private javax.swing.JLabel printerLabel3;
    private javax.swing.JLabel printerLabel4;
    private javax.swing.JLabel printerLabel5;
    private javax.swing.JLabel printerLabel6;
    private javax.swing.JLabel printerLabel7;
    private javax.swing.JLabel printerLabel8;
    private javax.swing.JLabel printerLabel9;
    private javax.swing.JRadioButton radioButton1;
    private javax.swing.JRadioButton radioButton10;
    private javax.swing.JRadioButton radioButton10p;
    private javax.swing.JRadioButton radioButton1p;
    private javax.swing.JRadioButton radioButton2;
    private javax.swing.JRadioButton radioButton20;
    private javax.swing.JRadioButton radioButton20p;
    private javax.swing.JRadioButton radioButton2p;
    private javax.swing.JRadioButton radioButton5;
    private javax.swing.JRadioButton radioButton50;
    private javax.swing.JRadioButton radioButton50p;
    private javax.swing.JRadioButton radioButton5p;
    private javax.swing.JLabel rwLabel;
    private javax.swing.JLabel sgiLabel;
    private javax.swing.JLabel shaLabel;
    private javax.swing.JLabel slLabel;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JLabel subunitLabel2;
    private javax.swing.JLabel taLabel;
    private javax.swing.JLabel terLabel;
    private javax.swing.JLabel ugLabel;
    private javax.swing.JLabel ukLabel;
    private javax.swing.JLabel unofficialUserLabel;
    private javax.swing.JPanel userTab;
    private javax.swing.JLabel zaLabel;
    private javax.swing.JLabel ziLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (radioButton5.isSelected() ||
                radioButton10.isSelected() ||
                radioButton20.isSelected() ||
                radioButton50.isSelected()) {
        banknotePicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        } else {
            coinPicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        }
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = GBPinfo.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(JFrame, "File Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
  
}
