/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adam.convertcurrency;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Bodie
 */
public class INRinfo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form INRinfo
     */
    static String inr50pc = "INR50pc";
    static String inr1c = "INR1c";
    static String inr2c = "INR2c";
    static String inr5c = "INR5c";
    static String inr10c = "INR10c";
    static String inr5 = "INR5";
    static String inr10 = "INR10";
    static String inr20 = "INR20";
    static String inr50 = "INR50";
    static String inr100 = "INR100";
    static String inr500 = "INR500";
    static String inr1000 = "INR1000";
    private static Component JFrame;
    
    public INRinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inrButtonGroup = new javax.swing.ButtonGroup();
        inrInfoTab = new javax.swing.JTabbedPane();
        infoTab = new javax.swing.JPanel();
        radioButton5 = new javax.swing.JRadioButton(inr5);
        radioButton10 = new javax.swing.JRadioButton(inr10);
        radioButton20 = new javax.swing.JRadioButton(inr20);
        radioButton50 = new javax.swing.JRadioButton(inr50);
        radioButton100 = new javax.swing.JRadioButton(inr100);
        radioButton500 = new javax.swing.JRadioButton(inr500);
        radioButton1000 = new javax.swing.JRadioButton(inr1000);
        banknotePicture = new javax.swing.JLabel(createImageIcon(""));
        jSeparator1 = new javax.swing.JSeparator();
        coin = new javax.swing.JLabel();
        radioButton50pc = new javax.swing.JRadioButton(inr50pc);
        radioButton1c = new javax.swing.JRadioButton(inr1c);
        radioButton2c = new javax.swing.JRadioButton(inr2c);
        radioButton5c = new javax.swing.JRadioButton(inr5c);
        radioButton10c = new javax.swing.JRadioButton(inr10c);
        coinPicture = new javax.swing.JLabel();
        banknote = new javax.swing.JLabel();
        userTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        officialUserLabel = new javax.swing.JLabel();
        unofficialUserLabel = new javax.swing.JLabel();
        indLabel = new javax.swing.JLabel();
        bhuLabel = new javax.swing.JLabel();
        otherTab = new javax.swing.JPanel();
        isoLabel = new javax.swing.JLabel();
        isoLabel2 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        bankLabel2 = new javax.swing.JLabel();
        pegLabel = new javax.swing.JLabel();
        pegLabel1 = new javax.swing.JLabel();
        pegLabel2 = new javax.swing.JLabel();
        inflationLabel = new javax.swing.JLabel();
        inflationLabel2 = new javax.swing.JLabel();
        printerLabel = new javax.swing.JLabel();
        printerLabel2 = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        subunitLabel2 = new javax.swing.JLabel();
        symbolLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inrInfoTitle = new javax.swing.JLabel();

        setTitle("Indian Rupee");

        inrButtonGroup.add(radioButton5);
        radioButton5.setText("Rs5");
        radioButton5.setActionCommand(inr5);
        radioButton5.addActionListener(this);

        inrButtonGroup.add(radioButton10);
        radioButton10.setText("Rs10");
        radioButton10.setActionCommand(inr10);
        radioButton10.addActionListener(this);

        inrButtonGroup.add(radioButton20);
        radioButton20.setText("Rs20");
        radioButton20.setActionCommand(inr20);
        radioButton20.addActionListener(this);

        inrButtonGroup.add(radioButton50);
        radioButton50.setText("Rs50");
        radioButton50.setActionCommand(inr50);
        radioButton50.addActionListener(this);

        inrButtonGroup.add(radioButton100);
        radioButton100.setText("Rs100");
        radioButton100.setActionCommand(inr100);
        radioButton100.addActionListener(this);

        inrButtonGroup.add(radioButton500);
        radioButton500.setText("Rs500");
        radioButton500.setActionCommand(inr500);
        radioButton500.addActionListener(this);

        inrButtonGroup.add(radioButton1000);
        radioButton1000.setText("Rs1000");
        radioButton1000.setActionCommand(inr1000);
        radioButton1000.addActionListener(this);

        banknotePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin.setText("Coin");

        inrButtonGroup.add(radioButton50pc);
        radioButton50pc.setText("50 paise");
        radioButton50pc.setActionCommand(inr50pc);
        radioButton50pc.addActionListener(this);

        inrButtonGroup.add(radioButton1c);
        radioButton1c.setText("Rs1");
        radioButton1c.setActionCommand(inr1c);
        radioButton1c.addActionListener(this);

        inrButtonGroup.add(radioButton2c);
        radioButton2c.setText("Rs2");
        radioButton2c.setActionCommand(inr2c);
        radioButton2c.addActionListener(this);

        inrButtonGroup.add(radioButton5c);
        radioButton5c.setText("Rs5");
        radioButton5c.setActionCommand(inr5c);
        radioButton5c.addActionListener(this);

        inrButtonGroup.add(radioButton10c);
        radioButton10c.setText("Rs10");
        radioButton10c.setActionCommand(inr10c);
        radioButton10c.addActionListener(this);

        coinPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        banknote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banknote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banknote.setText("Banknote");

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(radioButton50pc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton1c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton2c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton5c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton10c))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(infoTabLayout.createSequentialGroup()
                                .addComponent(radioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton500)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton1000))
                            .addComponent(banknote, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(coin, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banknote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5)
                    .addComponent(radioButton10)
                    .addComponent(radioButton20)
                    .addComponent(radioButton50)
                    .addComponent(radioButton100)
                    .addComponent(radioButton500)
                    .addComponent(radioButton1000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton1c)
                    .addComponent(radioButton2c)
                    .addComponent(radioButton5c)
                    .addComponent(radioButton10c)
                    .addComponent(radioButton50pc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        inrInfoTab.addTab("Info", infoTab);

        officialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officialUserLabel.setText("Official Users");

        unofficialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unofficialUserLabel.setText("Unofficial Users");

        indLabel.setText("India");

        bhuLabel.setText("Bhutan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officialUserLabel)
                    .addComponent(unofficialUserLabel)
                    .addComponent(indLabel)
                    .addComponent(bhuLabel))
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(officialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indLabel)
                .addGap(18, 18, 18)
                .addComponent(unofficialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bhuLabel)
                .addGap(310, 310, 310))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        inrInfoTab.addTab("Users", userTab);

        isoLabel.setText("ISO 4217 Code:");

        isoLabel2.setText("INR");

        bankLabel.setText("Central Bank:");

        bankLabel2.setText("Reserve Bank of India");

        pegLabel.setText("Pegged by: ");

        pegLabel1.setText("Bhutanese ngultrum (at par)");

        pegLabel2.setText("Nepalese rupee (1 INR = 1.6 NPR)");

        inflationLabel.setText("Inflation:");

        inflationLabel2.setText("5.96%");

        printerLabel.setText("Printer:");

        printerLabel2.setText("Reserve Bank of India");

        subunitLabel.setText("Subunit:");

        subunitLabel2.setText("1/100 (Paisa)");

        symbolLabel.setText("Official Currency Symbol:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INRsymbol.gif"))); // NOI18N

        javax.swing.GroupLayout otherTabLayout = new javax.swing.GroupLayout(otherTab);
        otherTab.setLayout(otherTabLayout);
        otherTabLayout.setHorizontalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(symbolLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(subunitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subunitLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(printerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printerLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(inflationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inflationLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(bankLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(isoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(pegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pegLabel2)
                            .addComponent(pegLabel1))))
                .addContainerGap())
        );
        otherTabLayout.setVerticalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isoLabel)
                    .addComponent(isoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankLabel)
                    .addComponent(bankLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pegLabel)
                    .addComponent(pegLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subunitLabel)
                    .addComponent(subunitLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationLabel)
                    .addComponent(inflationLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printerLabel)
                    .addComponent(printerLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symbolLabel)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        inrInfoTab.addTab("Other", otherTab);

        inrInfoTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inrInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inrInfoTitle.setText("Indian Rupee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inrInfoTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(inrInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inrInfoTitle)
                .addGap(18, 18, 18)
                .addComponent(inrInfoTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INRinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INRinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INRinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INRinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INRinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JLabel banknote;
    private javax.swing.JLabel banknotePicture;
    private javax.swing.JLabel bhuLabel;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinPicture;
    private javax.swing.JLabel indLabel;
    private javax.swing.JLabel inflationLabel;
    private javax.swing.JLabel inflationLabel2;
    private javax.swing.JPanel infoTab;
    private javax.swing.ButtonGroup inrButtonGroup;
    private javax.swing.JTabbedPane inrInfoTab;
    private javax.swing.JLabel inrInfoTitle;
    private javax.swing.JLabel isoLabel;
    private javax.swing.JLabel isoLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel officialUserLabel;
    private javax.swing.JPanel otherTab;
    private javax.swing.JLabel pegLabel;
    private javax.swing.JLabel pegLabel1;
    private javax.swing.JLabel pegLabel2;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JLabel printerLabel2;
    private javax.swing.JRadioButton radioButton10;
    private javax.swing.JRadioButton radioButton100;
    private javax.swing.JRadioButton radioButton1000;
    private javax.swing.JRadioButton radioButton10c;
    private javax.swing.JRadioButton radioButton1c;
    private javax.swing.JRadioButton radioButton20;
    private javax.swing.JRadioButton radioButton2c;
    private javax.swing.JRadioButton radioButton5;
    private javax.swing.JRadioButton radioButton50;
    private javax.swing.JRadioButton radioButton500;
    private javax.swing.JRadioButton radioButton50pc;
    private javax.swing.JRadioButton radioButton5c;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JLabel subunitLabel2;
    private javax.swing.JLabel symbolLabel;
    private javax.swing.JLabel unofficialUserLabel;
    private javax.swing.JPanel userTab;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (radioButton5.isSelected() ||
                radioButton10.isSelected() ||
                radioButton20.isSelected() ||
                radioButton50.isSelected() ||
                radioButton100.isSelected() ||
                radioButton500.isSelected() ||
                radioButton1000.isSelected()) {
        banknotePicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        } else {
            coinPicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        }
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = INRinfo.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(JFrame, "File Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
  
}
