/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adam.convertcurrency;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Bodie
 */
public class MXNinfo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form MXNinfo
     */
    static String mxn1c = "MXN1c";
    static String mxn2c = "MXN2c";
    static String mxn5c = "MXN5c";
    static String mxn10c = "MXN10c";
    static String mxn20c = "MXN20c";
    static String mxn50c = "MXN50c";
    static String mxn100c = "MXN100c";
    static String mxn5cc = "MXN5cc";
    static String mxn10cc = "MXN10cc";
    static String mxn20cc = "MXN20cc";
    private String mxn50cc = "MXN50cc";
    static String mxn20 = "MXN20";
    static String mxn50 = "MXN50";
    static String mxn100 = "MXN100";
    static String mxn200 = "MXN200";
    static String mxn500 = "MXN500";
    static String mxn1000 = "MXN1000";
    private static Component JFrame;
    
    
    public MXNinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mxnButtonGroup = new javax.swing.ButtonGroup();
        mxnInfoTab = new javax.swing.JTabbedPane();
        infoTab = new javax.swing.JPanel();
        radioButton20 = new javax.swing.JRadioButton(mxn20);
        radioButton50 = new javax.swing.JRadioButton(mxn50);
        radioButton100 = new javax.swing.JRadioButton(mxn100);
        radioButton200 = new javax.swing.JRadioButton(mxn200);
        radioButton500 = new javax.swing.JRadioButton(mxn500);
        radioButton1000 = new javax.swing.JRadioButton(mxn1000);
        banknotePicture = new javax.swing.JLabel(createImageIcon(""));
        jSeparator1 = new javax.swing.JSeparator();
        coin = new javax.swing.JLabel();
        radioButton5cc = new javax.swing.JRadioButton(mxn5cc);
        radioButton10cc = new javax.swing.JRadioButton(mxn10cc);
        radioButton20cc = new javax.swing.JRadioButton(mxn20cc);
        radioButton50cc = new javax.swing.JRadioButton(mxn50cc);
        radioButton1c = new javax.swing.JRadioButton(mxn1c);
        radioButton2c = new javax.swing.JRadioButton(mxn2c);
        radioButton5c = new javax.swing.JRadioButton(mxn5c);
        radioButton10c = new javax.swing.JRadioButton(mxn10c);
        radioButton20c = new javax.swing.JRadioButton(mxn20c);
        radioButton50c = new javax.swing.JRadioButton(mxn50c);
        radioButton100c = new javax.swing.JRadioButton(mxn100c);
        coinPicture = new javax.swing.JLabel();
        banknote = new javax.swing.JLabel();
        userTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        officialUserLabel = new javax.swing.JLabel();
        mxnLabel = new javax.swing.JLabel();
        otherTab = new javax.swing.JPanel();
        isoLabel = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        inflationLabel = new javax.swing.JLabel();
        printerLabel = new javax.swing.JLabel();
        isoLabel2 = new javax.swing.JLabel();
        bankLabel2 = new javax.swing.JLabel();
        inflationLabel2 = new javax.swing.JLabel();
        printerLabel2 = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        subunitLabel2 = new javax.swing.JLabel();
        mxnInfoTitle = new javax.swing.JLabel();

        setTitle("Mexican Peso");

        mxnButtonGroup.add(radioButton20);
        radioButton20.setText("$20");
        radioButton20.setActionCommand(mxn20);
        radioButton20.addActionListener(this);

        mxnButtonGroup.add(radioButton50);
        radioButton50.setText("$50");
        radioButton50.setActionCommand(mxn50);
        radioButton50.addActionListener(this);

        mxnButtonGroup.add(radioButton100);
        radioButton100.setText("$100");
        radioButton100.setActionCommand(mxn100);
        radioButton100.addActionListener(this);

        mxnButtonGroup.add(radioButton200);
        radioButton200.setText("$200");
        radioButton200.setActionCommand(mxn200);
        radioButton200.addActionListener(this);

        mxnButtonGroup.add(radioButton500);
        radioButton500.setText("$500");
        radioButton500.setActionCommand(mxn500);
        radioButton500.addActionListener(this);

        mxnButtonGroup.add(radioButton1000);
        radioButton1000.setText("$1000");
        radioButton1000.setActionCommand(mxn1000);
        radioButton1000.addActionListener(this);

        banknotePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin.setText("Coin");

        mxnButtonGroup.add(radioButton5cc);
        radioButton5cc.setText("5c");
        radioButton5cc.setActionCommand(mxn5cc);
        radioButton5cc.addActionListener(this);

        mxnButtonGroup.add(radioButton10cc);
        radioButton10cc.setText("10c");
        radioButton10cc.setActionCommand(mxn10cc);
        radioButton10cc.addActionListener(this);

        mxnButtonGroup.add(radioButton20cc);
        radioButton20cc.setText("20c");
        radioButton20cc.setActionCommand(mxn20cc);
        radioButton20cc.addActionListener(this);

        mxnButtonGroup.add(radioButton50cc);
        radioButton50cc.setText("50c");
        radioButton50cc.setActionCommand(mxn50cc);
        radioButton50cc.addActionListener(this);

        mxnButtonGroup.add(radioButton1c);
        radioButton1c.setText("$1");
        radioButton1c.setActionCommand(mxn1c);
        radioButton1c.addActionListener(this);

        mxnButtonGroup.add(radioButton2c);
        radioButton2c.setText("$2");
        radioButton2c.setActionCommand(mxn2c);
        radioButton2c.addActionListener(this);

        mxnButtonGroup.add(radioButton5c);
        radioButton5c.setText("$5");
        radioButton5c.setActionCommand(mxn5c);
        radioButton5c.addActionListener(this);

        mxnButtonGroup.add(radioButton10c);
        radioButton10c.setText("$10");
        radioButton10c.setActionCommand(mxn10c);
        radioButton10c.addActionListener(this);

        mxnButtonGroup.add(radioButton20c);
        radioButton20c.setText("$20");
        radioButton20c.setActionCommand(mxn20c);
        radioButton20c.addActionListener(this);

        mxnButtonGroup.add(radioButton50c);
        radioButton50c.setText("$50");
        radioButton50c.setActionCommand(mxn50c);
        radioButton50c.addActionListener(this);

        mxnButtonGroup.add(radioButton100c);
        radioButton100c.setText("$100");
        radioButton100c.setActionCommand(mxn100c);
        radioButton100c.addActionListener(this);

        coinPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        banknote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banknote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banknote.setText("Banknote");

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(radioButton20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton200)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton1000))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(radioButton5cc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoTabLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(coin, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(infoTabLayout.createSequentialGroup()
                                .addComponent(radioButton10cc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton20cc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton50cc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton1c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton2c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton5c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton10c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton20c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton50c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButton100c))))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(banknote, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banknote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton50)
                    .addComponent(radioButton100)
                    .addComponent(radioButton200)
                    .addComponent(radioButton500)
                    .addComponent(radioButton1000)
                    .addComponent(radioButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton10c)
                    .addComponent(radioButton20c)
                    .addComponent(radioButton50c)
                    .addComponent(radioButton100c)
                    .addComponent(radioButton5c)
                    .addComponent(radioButton2c)
                    .addComponent(radioButton20cc)
                    .addComponent(radioButton50cc)
                    .addComponent(radioButton10cc)
                    .addComponent(radioButton5cc)
                    .addComponent(radioButton1c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        mxnInfoTab.addTab("Info", infoTab);

        officialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officialUserLabel.setText("Official Users");

        mxnLabel.setText("Mexico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officialUserLabel)
                    .addComponent(mxnLabel))
                .addGap(166, 166, 166))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(officialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mxnLabel)
                .addGap(430, 430, 430))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        mxnInfoTab.addTab("Users", userTab);

        isoLabel.setText("ISO 4217 Code:");

        bankLabel.setText("Central Bank:");

        inflationLabel.setText("Inflation:");

        printerLabel.setText("Printer:");

        isoLabel2.setText("MXN");

        bankLabel2.setText("Bank of Mexico");

        inflationLabel2.setText("3.97%");

        printerLabel2.setText("Bank of Mexico");

        subunitLabel.setText("Subunit:");

        subunitLabel2.setText("1/100 (Centavo)");

        javax.swing.GroupLayout otherTabLayout = new javax.swing.GroupLayout(otherTab);
        otherTab.setLayout(otherTabLayout);
        otherTabLayout.setHorizontalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(subunitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subunitLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(printerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printerLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(inflationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inflationLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(bankLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankLabel2))
                    .addGroup(otherTabLayout.createSequentialGroup()
                        .addComponent(isoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoLabel2)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        otherTabLayout.setVerticalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isoLabel)
                    .addComponent(isoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankLabel)
                    .addComponent(bankLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subunitLabel)
                    .addComponent(subunitLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationLabel)
                    .addComponent(inflationLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printerLabel)
                    .addComponent(printerLabel2))
                .addContainerGap(447, Short.MAX_VALUE))
        );

        mxnInfoTab.addTab("Other", otherTab);

        mxnInfoTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mxnInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mxnInfoTitle.setText("Mexican Peso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mxnInfoTab, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(mxnInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mxnInfoTitle)
                .addGap(18, 18, 18)
                .addComponent(mxnInfoTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MXNinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MXNinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MXNinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MXNinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MXNinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JLabel banknote;
    private javax.swing.JLabel banknotePicture;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinPicture;
    private javax.swing.JLabel inflationLabel;
    private javax.swing.JLabel inflationLabel2;
    private javax.swing.JPanel infoTab;
    private javax.swing.JLabel isoLabel;
    private javax.swing.JLabel isoLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup mxnButtonGroup;
    private javax.swing.JTabbedPane mxnInfoTab;
    private javax.swing.JLabel mxnInfoTitle;
    private javax.swing.JLabel mxnLabel;
    private javax.swing.JLabel officialUserLabel;
    private javax.swing.JPanel otherTab;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JLabel printerLabel2;
    private javax.swing.JRadioButton radioButton100;
    private javax.swing.JRadioButton radioButton1000;
    private javax.swing.JRadioButton radioButton100c;
    private javax.swing.JRadioButton radioButton10c;
    private javax.swing.JRadioButton radioButton10cc;
    private javax.swing.JRadioButton radioButton1c;
    private javax.swing.JRadioButton radioButton20;
    private javax.swing.JRadioButton radioButton200;
    private javax.swing.JRadioButton radioButton20c;
    private javax.swing.JRadioButton radioButton20cc;
    private javax.swing.JRadioButton radioButton2c;
    private javax.swing.JRadioButton radioButton50;
    private javax.swing.JRadioButton radioButton500;
    private javax.swing.JRadioButton radioButton50c;
    private javax.swing.JRadioButton radioButton50cc;
    private javax.swing.JRadioButton radioButton5c;
    private javax.swing.JRadioButton radioButton5cc;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JLabel subunitLabel2;
    private javax.swing.JPanel userTab;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (radioButton20.isSelected() ||
                radioButton50.isSelected() ||
                radioButton100.isSelected() ||
                radioButton200.isSelected() ||
                radioButton500.isSelected() ||
                radioButton1000.isSelected()) {
        banknotePicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        } else {
            coinPicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        }
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = MXNinfo.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(JFrame, "File Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
  
}
