/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adam.convertcurrency;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Bodie
 */
public class USDinfo extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form USDinfo
     */
    static String usd1c = "USD1c";
    static String usd5c = "USD5c";
    static String usd10c = "USD10c";
    static String usd25c = "USD25c";
    static String usd50c = "USD50c";
    static String usd1dc = "USD$1coin";
    static String usd1 = "USD$1";
    static String usd2 = "USD$2";
    static String usd5 = "USD$5";
    static String usd10 = "USD$10";
    static String usd20 = "USD$20";
    static String usd50 = "USD$50";
    static String usd100 = "USD$100";
    private static Component JFrame;
    
    public USDinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usdButtonGroup = new javax.swing.ButtonGroup();
        usdInfoTab = new javax.swing.JTabbedPane();
        infoTab = new javax.swing.JPanel();
        radioButton5d = new javax.swing.JRadioButton(usd5);
        radioButton10d = new javax.swing.JRadioButton(usd10);
        radioButton20d = new javax.swing.JRadioButton(usd20);
        radioButton50d = new javax.swing.JRadioButton(usd50);
        radioButton100d = new javax.swing.JRadioButton(usd100);
        banknotePicture = new javax.swing.JLabel(createImageIcon(""));
        jSeparator1 = new javax.swing.JSeparator();
        coin = new javax.swing.JLabel();
        radioButton5c = new javax.swing.JRadioButton(usd5c);
        radioButton10c = new javax.swing.JRadioButton(usd10c);
        radioButton25c = new javax.swing.JRadioButton(usd25c);
        radioButton50c = new javax.swing.JRadioButton(usd50c);
        radioButton1dc = new javax.swing.JRadioButton(usd1dc);
        radioButton1c = new javax.swing.JRadioButton(usd1c);
        coinPicture = new javax.swing.JLabel();
        banknote = new javax.swing.JLabel();
        radioButton2d = new javax.swing.JRadioButton(usd2);
        radioButton1d = new javax.swing.JRadioButton(usd1);
        userTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        officialUserLabel = new javax.swing.JLabel();
        usLabel = new javax.swing.JLabel();
        ecLabel = new javax.swing.JLabel();
        etLabel = new javax.swing.JLabel();
        elLabel = new javax.swing.JLabel();
        paLabel = new javax.swing.JLabel();
        terLabel = new javax.swing.JLabel();
        asLabel = new javax.swing.JLabel();
        guLabel = new javax.swing.JLabel();
        nmLabel = new javax.swing.JLabel();
        prLabel = new javax.swing.JLabel();
        usvLabel = new javax.swing.JLabel();
        usmLabel = new javax.swing.JLabel();
        unofficialUserLabel = new javax.swing.JLabel();
        afLabel = new javax.swing.JLabel();
        baLabel = new javax.swing.JLabel();
        brLabel = new javax.swing.JLabel();
        caLabel = new javax.swing.JLabel();
        gtLabel = new javax.swing.JLabel();
        haLabel = new javax.swing.JLabel();
        leLabel = new javax.swing.JLabel();
        liLabel = new javax.swing.JLabel();
        maLabel = new javax.swing.JLabel();
        miLabel = new javax.swing.JLabel();
        mcLabel = new javax.swing.JLabel();
        plLabel = new javax.swing.JLabel();
        ziLabel = new javax.swing.JLabel();
        oterLabel = new javax.swing.JLabel();
        berLabel = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        bviLabel = new javax.swing.JLabel();
        cnLabel = new javax.swing.JLabel();
        cyLabel = new javax.swing.JLabel();
        tcLabel = new javax.swing.JLabel();
        otherTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        isoLabel = new javax.swing.JLabel();
        isoLabel2 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        bankLabel2 = new javax.swing.JLabel();
        pegLabel = new javax.swing.JLabel();
        pegLabel1 = new javax.swing.JLabel();
        pegLabel2 = new javax.swing.JLabel();
        pegLabel3 = new javax.swing.JLabel();
        pegLabel4 = new javax.swing.JLabel();
        pegLabel5 = new javax.swing.JLabel();
        pegLabel6 = new javax.swing.JLabel();
        pegLabel7 = new javax.swing.JLabel();
        pegLabel8 = new javax.swing.JLabel();
        pegLabel9 = new javax.swing.JLabel();
        pegLabel10 = new javax.swing.JLabel();
        pegLabel11 = new javax.swing.JLabel();
        pegLabel12 = new javax.swing.JLabel();
        pegLabel13 = new javax.swing.JLabel();
        pegLabel14 = new javax.swing.JLabel();
        pegLabel15 = new javax.swing.JLabel();
        pegLabel16 = new javax.swing.JLabel();
        pegLabel17 = new javax.swing.JLabel();
        pegLabel18 = new javax.swing.JLabel();
        pegLabel19 = new javax.swing.JLabel();
        pegLabel20 = new javax.swing.JLabel();
        pegLabel21 = new javax.swing.JLabel();
        pegLabel22 = new javax.swing.JLabel();
        inflationLabel = new javax.swing.JLabel();
        inflationLabel2 = new javax.swing.JLabel();
        printerLabel = new javax.swing.JLabel();
        printerLabel2 = new javax.swing.JLabel();
        subunitLabel = new javax.swing.JLabel();
        subunitLabel2 = new javax.swing.JLabel();
        usdInfoTitle = new javax.swing.JLabel();

        setTitle("United States Dollar");

        usdButtonGroup.add(radioButton5d);
        radioButton5d.setText("$5");
        radioButton5d.setActionCommand(usd5);
        radioButton5d.addActionListener(this);

        usdButtonGroup.add(radioButton10d);
        radioButton10d.setText("$10");
        radioButton10d.setActionCommand(usd10);
        radioButton10d.addActionListener(this);

        usdButtonGroup.add(radioButton20d);
        radioButton20d.setText("$20");
        radioButton20d.setActionCommand(usd20);
        radioButton20d.addActionListener(this);

        usdButtonGroup.add(radioButton50d);
        radioButton50d.setText("$50");
        radioButton50d.setActionCommand(usd50);
        radioButton50d.addActionListener(this);

        usdButtonGroup.add(radioButton100d);
        radioButton100d.setText("$100");
        radioButton100d.setActionCommand(usd100);
        radioButton100d.addActionListener(this);

        banknotePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin.setText("Coin");

        usdButtonGroup.add(radioButton5c);
        radioButton5c.setText("5¢");
        radioButton5c.setActionCommand(usd5c);
        radioButton5c.addActionListener(this);

        usdButtonGroup.add(radioButton10c);
        radioButton10c.setText("10¢");
        radioButton10c.setActionCommand(usd10c);
        radioButton10c.addActionListener(this);

        usdButtonGroup.add(radioButton25c);
        radioButton25c.setText("25¢");
        radioButton25c.setActionCommand(usd25c);
        radioButton25c.addActionListener(this);

        usdButtonGroup.add(radioButton50c);
        radioButton50c.setText("50¢");
        radioButton50c.setActionCommand(usd50c);
        radioButton50c.addActionListener(this);

        usdButtonGroup.add(radioButton1dc);
        radioButton1dc.setText("$1");
        radioButton1dc.setActionCommand(usd1dc);
        radioButton1dc.addActionListener(this);

        usdButtonGroup.add(radioButton1c);
        radioButton1c.setText("1¢");
        radioButton1c.setActionCommand(usd1c);
        radioButton1c.addActionListener(this);

        coinPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        banknote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banknote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banknote.setText("Banknote");

        usdButtonGroup.add(radioButton2d);
        radioButton2d.setText("$2");
        radioButton2d.setActionCommand(usd2);
        radioButton2d.addActionListener(this);

        usdButtonGroup.add(radioButton1d);
        radioButton1d.setText("$1");
        radioButton1d.setActionCommand(usd1);
        radioButton1d.addActionListener(this);

        javax.swing.GroupLayout infoTabLayout = new javax.swing.GroupLayout(infoTab);
        infoTab.setLayout(infoTabLayout);
        infoTabLayout.setHorizontalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(radioButton1c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton5c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton10c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton25c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton50c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton1dc))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(radioButton1d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton2d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton5d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton10d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton20d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton50d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton100d))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(banknote, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(coin, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        infoTabLayout.setVerticalGroup(
            infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banknote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5d)
                    .addComponent(radioButton10d)
                    .addComponent(radioButton20d)
                    .addComponent(radioButton50d)
                    .addComponent(radioButton100d)
                    .addComponent(radioButton2d)
                    .addComponent(radioButton1d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(banknotePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton5c)
                    .addComponent(radioButton10c)
                    .addComponent(radioButton25c)
                    .addComponent(radioButton50c)
                    .addComponent(radioButton1dc)
                    .addComponent(radioButton1c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coinPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        usdInfoTab.addTab("Info", infoTab);

        officialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officialUserLabel.setText("Official Users");

        usLabel.setText("United States");

        ecLabel.setText("Ecuador");

        etLabel.setText("East Timor");

        elLabel.setText("El Salvador");

        paLabel.setText("Panama");

        terLabel.setText("United States Territories");

        asLabel.setText("American Samoa");

        guLabel.setText("Guam");

        nmLabel.setText("Northern Mariana Islands");

        prLabel.setText("Puerto Rico");

        usvLabel.setText("U.S. Virgin Islands");

        usmLabel.setText("United States Minor Outlying Islands");

        unofficialUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unofficialUserLabel.setText("Unofficial Users");

        afLabel.setText("Afghanistan");

        baLabel.setText("The Bahamas");

        brLabel.setText("Barbados");

        caLabel.setText("Cambodia");

        gtLabel.setText("Guatemala");

        haLabel.setText("Haiti");

        leLabel.setText("Lebanon");

        liLabel.setText("Liberia");

        maLabel.setText("Maldives");

        miLabel.setText("Marshall Islands");

        mcLabel.setText("Federated States of Micronesia");

        plLabel.setText("Palau");

        ziLabel.setText("Zimbabwe");

        oterLabel.setText("Other Territories");

        berLabel.setText("Bermuda (United Kingdom)");

        bioLabel.setText("British Indian Ocean Territory (United Kingdom)");

        bviLabel.setText("British Virgin Island (United Kingdom)");

        cnLabel.setText("Caribbean Netherlands (Netherlands)");

        cyLabel.setText("Cayman Islands (United Kingdom)");

        tcLabel.setText("Turks and Caicos Islands (United Kingdom)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bviLabel)
                    .addComponent(tcLabel)
                    .addComponent(etLabel)
                    .addComponent(officialUserLabel)
                    .addComponent(terLabel)
                    .addComponent(oterLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ecLabel)
                            .addComponent(usLabel)))
                    .addComponent(paLabel)
                    .addComponent(elLabel)
                    .addComponent(unofficialUserLabel)
                    .addComponent(miLabel)
                    .addComponent(maLabel)
                    .addComponent(liLabel)
                    .addComponent(leLabel)
                    .addComponent(haLabel)
                    .addComponent(gtLabel)
                    .addComponent(caLabel)
                    .addComponent(brLabel)
                    .addComponent(baLabel)
                    .addComponent(afLabel)
                    .addComponent(ziLabel)
                    .addComponent(plLabel)
                    .addComponent(mcLabel)
                    .addComponent(cyLabel)
                    .addComponent(cnLabel)
                    .addComponent(asLabel)
                    .addComponent(guLabel)
                    .addComponent(nmLabel)
                    .addComponent(prLabel)
                    .addComponent(usvLabel)
                    .addComponent(usmLabel)
                    .addComponent(berLabel)
                    .addComponent(bioLabel))
                .addGap(213, 213, 213))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(officialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ecLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usvLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usmLabel)
                .addGap(7, 7, 7)
                .addComponent(unofficialUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(haLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(liLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mcLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ziLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(berLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bviLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcLabel)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        usdInfoTab.addTab("Users", userTab);

        isoLabel.setText("ISO 4217 Code:");

        isoLabel2.setText("USD");

        bankLabel.setText("Central Bank:");

        bankLabel2.setText(" Federal Reserve System");

        pegLabel.setText("Pegged by: ");

        pegLabel1.setText("Aruban florin");

        pegLabel2.setText("Bahamian dollar (at par)");

        pegLabel3.setText("Bahraini dinar");

        pegLabel4.setText("Barbadian dollar");

        pegLabel5.setText("Belize dollar");

        pegLabel6.setText("Bermudian dollar (at par)");

        pegLabel7.setText("Cayman Islands dollar");

        pegLabel8.setText("Cuban convertible peso");

        pegLabel9.setText("Djiboutian franc");

        pegLabel10.setText("East Caribbean dollar");

        pegLabel11.setText("Eritrean nakfa");

        pegLabel12.setText("Hong Kong dollar (narrow band)");

        pegLabel13.setText("Jordanian dinar");

        pegLabel14.setText("Lebanese pound");

        pegLabel15.setText("Netherlands Antillean gulden");

        pegLabel16.setText("Omani rial");

        pegLabel17.setText("Panamanian balboa (at par)");

        pegLabel18.setText("Qatari riyal");

        pegLabel19.setText("Saudi riyal");

        pegLabel20.setText("Trinidad and Tobago dollar");

        pegLabel21.setText("United Arab Emirates dirham");

        pegLabel22.setText("Venezuelan bolívar");

        inflationLabel.setText("Inflation:");

        inflationLabel2.setText("2.13%");

        printerLabel.setText("Printer:");

        printerLabel2.setText("Bureau of Engraving and Printing");

        subunitLabel.setText("Subunit:");

        subunitLabel2.setText("1/100 (cent)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(isoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bankLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pegLabel4)
                            .addComponent(pegLabel5)
                            .addComponent(pegLabel6)
                            .addComponent(pegLabel2)
                            .addComponent(pegLabel3)
                            .addComponent(pegLabel1)
                            .addComponent(pegLabel11)
                            .addComponent(pegLabel10)
                            .addComponent(pegLabel7)
                            .addComponent(pegLabel8)
                            .addComponent(pegLabel9)
                            .addComponent(pegLabel12)
                            .addComponent(pegLabel13)
                            .addComponent(pegLabel14)
                            .addComponent(pegLabel15)
                            .addComponent(pegLabel16)
                            .addComponent(pegLabel17)
                            .addComponent(pegLabel18)
                            .addComponent(pegLabel19)
                            .addComponent(pegLabel20)
                            .addComponent(pegLabel21)
                            .addComponent(pegLabel22)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inflationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inflationLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(printerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printerLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(subunitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subunitLabel2)))
                .addGap(256, 256, 256))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isoLabel)
                    .addComponent(isoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankLabel)
                    .addComponent(bankLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pegLabel)
                    .addComponent(pegLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subunitLabel)
                    .addComponent(subunitLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inflationLabel)
                    .addComponent(inflationLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printerLabel)
                    .addComponent(printerLabel2))
                .addGap(33, 33, 33))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout otherTabLayout = new javax.swing.GroupLayout(otherTab);
        otherTab.setLayout(otherTabLayout);
        otherTabLayout.setHorizontalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        otherTabLayout.setVerticalGroup(
            otherTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        usdInfoTab.addTab("Other", otherTab);

        usdInfoTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usdInfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usdInfoTitle.setText("United States Dollar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usdInfoTab)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(usdInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usdInfoTitle)
                .addGap(18, 18, 18)
                .addComponent(usdInfoTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USDinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USDinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afLabel;
    private javax.swing.JLabel asLabel;
    private javax.swing.JLabel baLabel;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JLabel banknote;
    private javax.swing.JLabel banknotePicture;
    private javax.swing.JLabel berLabel;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JLabel brLabel;
    private javax.swing.JLabel bviLabel;
    private javax.swing.JLabel caLabel;
    private javax.swing.JLabel cnLabel;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinPicture;
    private javax.swing.JLabel cyLabel;
    private javax.swing.JLabel ecLabel;
    private javax.swing.JLabel elLabel;
    private javax.swing.JLabel etLabel;
    private javax.swing.JLabel gtLabel;
    private javax.swing.JLabel guLabel;
    private javax.swing.JLabel haLabel;
    private javax.swing.JLabel inflationLabel;
    private javax.swing.JLabel inflationLabel2;
    private javax.swing.JPanel infoTab;
    private javax.swing.JLabel isoLabel;
    private javax.swing.JLabel isoLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel leLabel;
    private javax.swing.JLabel liLabel;
    private javax.swing.JLabel maLabel;
    private javax.swing.JLabel mcLabel;
    private javax.swing.JLabel miLabel;
    private javax.swing.JLabel nmLabel;
    private javax.swing.JLabel officialUserLabel;
    private javax.swing.JLabel oterLabel;
    private javax.swing.JPanel otherTab;
    private javax.swing.JLabel paLabel;
    private javax.swing.JLabel pegLabel;
    private javax.swing.JLabel pegLabel1;
    private javax.swing.JLabel pegLabel10;
    private javax.swing.JLabel pegLabel11;
    private javax.swing.JLabel pegLabel12;
    private javax.swing.JLabel pegLabel13;
    private javax.swing.JLabel pegLabel14;
    private javax.swing.JLabel pegLabel15;
    private javax.swing.JLabel pegLabel16;
    private javax.swing.JLabel pegLabel17;
    private javax.swing.JLabel pegLabel18;
    private javax.swing.JLabel pegLabel19;
    private javax.swing.JLabel pegLabel2;
    private javax.swing.JLabel pegLabel20;
    private javax.swing.JLabel pegLabel21;
    private javax.swing.JLabel pegLabel22;
    private javax.swing.JLabel pegLabel3;
    private javax.swing.JLabel pegLabel4;
    private javax.swing.JLabel pegLabel5;
    private javax.swing.JLabel pegLabel6;
    private javax.swing.JLabel pegLabel7;
    private javax.swing.JLabel pegLabel8;
    private javax.swing.JLabel pegLabel9;
    private javax.swing.JLabel plLabel;
    private javax.swing.JLabel prLabel;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JLabel printerLabel2;
    private javax.swing.JRadioButton radioButton100d;
    private javax.swing.JRadioButton radioButton10c;
    private javax.swing.JRadioButton radioButton10d;
    private javax.swing.JRadioButton radioButton1c;
    private javax.swing.JRadioButton radioButton1d;
    private javax.swing.JRadioButton radioButton1dc;
    private javax.swing.JRadioButton radioButton20d;
    private javax.swing.JRadioButton radioButton25c;
    private javax.swing.JRadioButton radioButton2d;
    private javax.swing.JRadioButton radioButton50c;
    private javax.swing.JRadioButton radioButton50d;
    private javax.swing.JRadioButton radioButton5c;
    private javax.swing.JRadioButton radioButton5d;
    private javax.swing.JLabel subunitLabel;
    private javax.swing.JLabel subunitLabel2;
    private javax.swing.JLabel tcLabel;
    private javax.swing.JLabel terLabel;
    private javax.swing.JLabel unofficialUserLabel;
    private javax.swing.JLabel usLabel;
    private javax.swing.ButtonGroup usdButtonGroup;
    private javax.swing.JTabbedPane usdInfoTab;
    private javax.swing.JLabel usdInfoTitle;
    private javax.swing.JPanel userTab;
    private javax.swing.JLabel usmLabel;
    private javax.swing.JLabel usvLabel;
    private javax.swing.JLabel ziLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (    radioButton1d.isSelected() ||
                radioButton2d.isSelected() ||
                radioButton5d.isSelected() ||
                radioButton10d.isSelected() ||
                radioButton20d.isSelected() ||
                radioButton50d.isSelected() ||
                radioButton100d.isSelected()) {
        banknotePicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        } else {
            coinPicture.setIcon(createImageIcon("/"
                                        + e.getActionCommand()
                                        + ".gif"));
        }
    }
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = USDinfo.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            JOptionPane.showMessageDialog(JFrame, "File Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
  
}
