
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adam Bodie
 */
public class PasserRatingGUI extends javax.swing.JFrame {

    /**
     * Creates new form PasserRatingGUI
     */
    public PasserRatingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterValueDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        playerTextField = new javax.swing.JTextField();
        completionTextField = new javax.swing.JTextField();
        attemptTextField = new javax.swing.JTextField();
        yardTextField = new javax.swing.JTextField();
        touchdownTextField = new javax.swing.JTextField();
        interceptionTextField = new javax.swing.JTextField();
        playerLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        completionLabel = new javax.swing.JLabel();
        attemptLabel = new javax.swing.JLabel();
        yardLabel = new javax.swing.JLabel();
        touchdownLabel = new javax.swing.JLabel();
        passerRatingLabel = new javax.swing.JLabel();
        interceptionLabel = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        teamComboBox = new javax.swing.JComboBox();
        passerRatingFormattedTextField = new javax.swing.JFormattedTextField();

        enterValueDialog.setIconImage(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Please enter a value:");

        javax.swing.GroupLayout enterValueDialogLayout = new javax.swing.GroupLayout(enterValueDialog.getContentPane());
        enterValueDialog.getContentPane().setLayout(enterValueDialogLayout);
        enterValueDialogLayout.setHorizontalGroup(
            enterValueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterValueDialogLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
        );
        enterValueDialogLayout.setVerticalGroup(
            enterValueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterValueDialogLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NFL Passer Rating");

        attemptTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptTextFieldActionPerformed(evt);
            }
        });

        yardTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardTextFieldActionPerformed(evt);
            }
        });

        playerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerLabel.setText("Player");

        teamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamLabel.setText("Team");

        completionLabel.setText("Completions");

        attemptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attemptLabel.setText("Attempts");

        yardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yardLabel.setText("Yards");

        touchdownLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        touchdownLabel.setText("Touchdowns");

        passerRatingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passerRatingLabel.setText("Passer Rating");

        interceptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        interceptionLabel.setText("Interceptions");

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        teamComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arizona Cardinals", "Atlanta Falcons", "Baltimore Ravens", "Buffalo Bills", "Carolina Panthers", "Chicago Bears", "Cincinnati Bengals", "Cleveland Browns", "Dallas Cowboys", "Denver Broncos", "Detroit Lions", "Green Bay Packers", "Houston Texans", "Indianapolis Colts", "Jacksonville Jaguars", "Kansas City Chiefs", "Miami Dolphins", "Minnesota Vikings", "New England Patriots", "New Orleans Saints", "New York Giants", "New York Jets", "Oakland Raiders", "Philadelphia Eagles", "Pittsburgh Steelers", "San Diego Chargers", "San Francisco 49ers", "Seattle Seahawks", "St. Louis Rams", "Tampa Bay Buccaneers", "Tennessee Titans", "Washington Redskins" }));
        teamComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passerRatingFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(convertButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(completionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(completionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(attemptTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(attemptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(playerTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(playerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yardTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(passerRatingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(teamComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(touchdownTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(touchdownLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(interceptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(interceptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(teamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerLabel)
                    .addComponent(teamLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(touchdownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interceptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completionLabel)
                    .addComponent(attemptLabel)
                    .addComponent(yardLabel)
                    .addComponent(touchdownLabel)
                    .addComponent(interceptionLabel))
                .addGap(32, 32, 32)
                .addComponent(convertButton)
                .addGap(18, 18, 18)
                .addComponent(passerRatingFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passerRatingLabel)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attemptTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attemptTextFieldActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        double completionText = Double.parseDouble(completionTextField.getText());
        double attemptText = Double.parseDouble(attemptTextField.getText());
        double yardText = Double.parseDouble(yardTextField.getText());
        double touchdownText = Double.parseDouble(touchdownTextField.getText());
        double interceptionText = Double.parseDouble(interceptionTextField.getText());

        double A = ((completionText / attemptText) - .3) * 5;
			if (A < 0) {
				A = 0;
			} else if (A > 2.375) {
				A = 2.375;
			} else
				A = ((completionText / attemptText) - .3) * 5;
			double B = ((yardText / attemptText) - 3) * 0.25;
			if (B < 0) {
				B = 0;
			} else if (B > 2.375) {
				B = 2.375;
			} else
				B = ((yardText / attemptText) - 3) * 0.25;
			double C = (touchdownText / attemptText) * 20;
			if (C < 0) {
				C = 0;
			} else if (C > 2.375) {
				C = 2.375;
			} else
				C = (touchdownText / attemptText) * 20;
			double D = 2.375 - ((interceptionText / attemptText) * 25);
			if (D < 0) {
				D = 0;
			} else if (D > 2.375) {
				D = 2.375;
			} else
				D = 2.375 - ((interceptionText / attemptText) * 25);
			double E = ((A + B + C + D) / 6) * 100;
                        
                       passerRatingFormattedTextField.setValue(E);
                       passerRatingFormattedTextField.setEditable(false);
                       passerRatingFormattedTextField.setForeground(Color.red);
                       passerRatingFormattedTextField.setHorizontalAlignment(JTextField.CENTER);
                             
    }//GEN-LAST:event_convertButtonActionPerformed

    private void yardTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yardTextFieldActionPerformed

    private void teamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamComboBoxActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String teamName = (String)cb.getSelectedItem();
        // TODO add your handling code here:
    }//GEN-LAST:event_teamComboBoxActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasserRatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasserRatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasserRatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasserRatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasserRatingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attemptLabel;
    private javax.swing.JTextField attemptTextField;
    private javax.swing.JLabel completionLabel;
    private javax.swing.JTextField completionTextField;
    private javax.swing.JButton convertButton;
    private javax.swing.JDialog enterValueDialog;
    private javax.swing.JLabel interceptionLabel;
    private javax.swing.JTextField interceptionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField passerRatingFormattedTextField;
    private javax.swing.JLabel passerRatingLabel;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JTextField playerTextField;
    private javax.swing.JComboBox teamComboBox;
    private javax.swing.JLabel teamLabel;
    private javax.swing.JLabel touchdownLabel;
    private javax.swing.JTextField touchdownTextField;
    private javax.swing.JLabel yardLabel;
    private javax.swing.JTextField yardTextField;
    // End of variables declaration//GEN-END:variables
}
